### PR TITLE
Fix/separation

### LINKED ISSUE #271: Fix Generated COE pdf
Fix the content of coe pdf

### PR DESCRIPTION
**Pull request by C-Ivan-Bandilla**
### 🛠 Changes #271 

- Update genearation of COE file
- fix bugs
- Add package https://github.com/PHPOffice/PHPWord

needs  `winget install libreoffice`  `sudo apt install libreoffice `  but I didn't know if it works on Linux machine yet

Template file
loc   `public\storage\templates\document\Certificate of Appreciation.docx`
loc   `public\storage\templates\document\signature-placeholder.png`

[Certificate of Appreciation.docx](https://github.com/user-attachments/files/18709062/Certificate.of.Appreciation.docx)
signature-placeholder

### 🎥 Demos (Optional)
https://drive.google.com/file/d/1KP4KTbjDfZc9xXxMSb1CLR3alEVXaCU5/view?usp=sharing

### ✔️ Checklist
This is a set of criteria to ensure the correctness of your PR. Check each that applied.
- [x] Is `staging` the base branch of this PR?
- [x] Do your changes not reveal sensitive information, such as secrets, API keys, etc?
- [ ] Are there no erroneous console logs, debuggers, or leftover code in your changes?

Shall resolve #271

### CODE REVIEW

File: app/Http/Controllers/Separation/CoeController.php [hunk 1]
```diff
@@ -64,24 +70,87 @@ public function edit($coeRequest)
...
+        $issueMonth = Carbon::parse($issuedDate)->format('F');
+        $issueYear = Carbon::parse($issuedDate)->isoFormat('YYYY');
+
+        $values = [
+            // Long Names isnt shrinked
+            'EMPLOYEE_NAME' => $coeRequest->requestor->fullname,
+            'START_DATE' => $coeRequest->requestor->lifecycle->start_date,
+            'END_DATE' => $coeRequest->requestor->lifecycle->separated_at,
+            'JOB_TITLE' => $coeRequest->requestor->jobTitle->job_title,
+            'DEPT_NAME' => $coeRequest->requestor->jobTitle->department->department_name,
```
Comment (Carl-Tabuso) [inline app/Http/Controllers/Separation/CoeController.php:109]: is this not causing n+1 query to `requestor` relationship everytime. As far as im aware you're not loading this relationship in `IssueCoeRequests` livewire component.

Comment (C-Ivan-Bandilla) [reply app/Http/Controllers/Separation/CoeController.php:110]: I think this  ... 6355da9f2966cab1012da7c0cd39fd07e761b5f8

**Review by Carl-Tabuso — APPROVED** [review]
🚀
